# Generated by Django 4.0.4 on 2022-04-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_artist_room_delete_studentdata_delete_teachertdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='artists',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
