# Generated by Django 4.0.4 on 2022-04-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSummaryForm1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=10000)),
                ('length', models.IntegerField()),
                ('summary', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='PSummaryForm2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=10000)),
                ('length', models.IntegerField()),
                ('summary', models.CharField(max_length=10000)),
            ],
        ),
    ]
