# Generated by Django 4.0.4 on 2022-04-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PSummaryForm2',
            new_name='PSummary1',
        ),
        migrations.RenameModel(
            old_name='PSummaryForm1',
            new_name='PSummary2',
        ),
    ]
