# Generated by Django 4.0.4 on 2022-04-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_alter_psummary1_length_alter_psummary2_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psummary1',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='psummary2',
            name='length',
            field=models.IntegerField(),
        ),
    ]
