# Generated by Django 4.0.4 on 2022-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_alter_psummary1_length_alter_psummary2_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psummary1',
            name='summary',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='psummary2',
            name='summary',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
