# Generated by Django 4.0.4 on 2022-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0006_alter_psummary1_id_alter_psummary1_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('f1_submitted', models.BooleanField(default=False)),
                ('f2_submitted', models.BooleanField(default=False)),
            ],
        ),
    ]
