# Generated by Django 4.0.4 on 2022-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0008_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
