# Generated by Django 4.0.4 on 2022-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0010_rename_media_file_uploaded_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_contents', models.CharField(max_length=10000)),
                ('summary_of_file_contents', models.CharField(max_length=10000)),
                ('file_url', models.URLField()),
            ],
        ),
    ]
