# Generated by Django 4.0.4 on 2022-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0011_displayfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_contents',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='file',
            name='summary_of_file_contents',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
