# Generated by Django 4.0.4 on 2022-04-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0012_file_file_contents_file_summary_of_file_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_contents',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
