# Generated by Django 4.0.4 on 2022-04-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0013_alter_file_file_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='summary_of_file_contents',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='psummary1',
            name='paragraph',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='psummary1',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='psummary2',
            name='paragraph',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='psummary2',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=10000),
        ),
    ]
