# Generated by Django 4.0.4 on 2022-04-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0014_alter_file_summary_of_file_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_contents',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='file',
            name='summary_of_file_contents',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
