# Generated by Django 4.0.4 on 2022-05-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0016_alter_file_file_contents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displayfile',
            name='file_url',
        ),
        migrations.AddField(
            model_name='file',
            name='length',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='displayfile',
            name='file_contents',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='displayfile',
            name='summary_of_file_contents',
            field=models.TextField(max_length=10000),
        ),
    ]
