# Generated by Django 4.0.4 on 2022-05-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0017_remove_displayfile_file_url_file_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayfile',
            name='length',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
